---
title: DENV Model
author: Pragati Prasad
date: '2019-10-31'
slug: denv-model
categories: []
tags: []
---

Based on this:

Kong L, Wang J, Li Z, et al. Modeling the Heterogeneity of Dengue Transmission in a City. Int J Environ Res Public Health. 2018;15(6):1128. Published 2018 May 31. doi:10.3390/ijerph15061128

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6025315/


```{r}
suppressMessages(library(EpiModel))
```

```{r}

denv <-function(t, t0, parms) {
  with(as.list(c(t0, parms)), {
    
    numH <- sh.num + eh.num + ih.num + rh.num 
    numV <- sv.num + ev.num + iv.num

    lambdaH <- log(1 + ((alpha*rhoV*iv.num)/(kappa*numH)))
    lambdaV <- log(1 + ((alpha*rhoH*ih.num)/(kappa*numH)))
    
    dSh <- (muH*numH) - (kappa*lambdaH*sh.num) - (muH*sh.num)
    dEh <- (kappa*lambdaH*sh.num) - ((deltaH + muH)*eh.num)
    dIh <- (deltaH*eh.num) - ((gammaH + muH)*ih.num)
    dRh <- (gammaH*ih.num) -  (muH*rh.num)
    
    dSv <- (muV*numV) - (kappa*lambdaV*sv.num) - (muV*sv.num)
    dEv <- (kappa*lambdaV*sv.num) - ((deltaV + muV)*ev.num)
    dIv <- (deltaV*ev.num) - (muV*iv.num)
    
    list(c(dSh,
           dEh,
           dIh,
           dRh,
           dSv,
           dEv,
           dIv,
           se.flow <- (kappa*lambdaH*sh.num),
           ei.flow <- (deltaH*eh.num),
           ir.flow<- (gammaH*ih.num)
    ))
  })
}

```

```{r}
param <-param.dcm(alpha = 1,
                  rhoV = 0.5,
                  rhoH = 0.75,
                  muH = 1/(75*365),
                  muV = 1/21,
                  deltaH = 1/7,
                  deltaV = 1/10,
                  gammaH = 1/4.5,
                  kappa = c(0.1, 0.01, 0.001, 0.0001))
init <-init.dcm(sh.num = 12.8389e6,
                eh.num = 0,
                ih.num = 0,
                rh.num = 0,
                sv.num = 33000000,
                ev.num = 33000000,
                iv.num = 33000000,
                se.flow = 0,
                ei.flow = 0,
                ir.flow = 0)
control <-control.dcm(nsteps =200, new.mod = denv) 

sim <- dcm(param, init, control)

sim <- mutate_epi(sim, numH = sh.num + eh.num + ih.num + rh.num)
sim <- mutate_epi(sim, numV = sv.num + ev.num + iv.num)
sim <- mutate_epi(sim, 
                  symp.prev = ih.num / numH,
                  se.prop = se.flow / numH,
                  ei.prop = ei.flow / numH,
                  ir.prop = ir.flow / numH
)

plot(sim,y=c("sh.num", "eh.num", "ih.num", "rh.num"),legend="full", main = "Kappa = 0.1")
plot(sim,y=c("sh.num"),legend="full", main = "Susceptibles")
plot(sim,y=c("eh.num"),legend="full", main = "Pre-infectious")
plot(sim,y=c("ih.num"),legend="full", main = "Infectious")
plot(sim,y=c("rh.num"),legend="full", main = "Recovered")

plot(sim,y=c("symp.prev"),legend="full", main = "Proportional Prevalence", ylim = c(0, 0.5))

plot(sim,y=c("se.flow"),legend="full", main = "S -> E")
plot(sim,y=c("ei.flow"),legend="full", main = "E -> I")
plot(sim,y=c("ir.flow"),legend="full", main = "I -> R")

plot(sim,y=c("se.prop"),legend="full", main = "Proportional S -> E", ylim = c(0, 0.225))
plot(sim,y=c("ei.prop"),legend="full", main = "Proportional E -> I", ylim = c(0, 0.1))
plot(sim,y=c("ir.prop"),legend="full", main = "Proportional I -> R", ylim = c(0, 0.1))

```





